# 🏗️ Basado en la imagen oficial de PostgreSQL 16
FROM postgres:16

# 🛠️ Ejecutar como root para configurar el sistema de archivos
USER root

# 📂 **Crear directorio de backups y asignar permisos**
RUN mkdir -p /backups && chmod -R 777 /backups && chown -R postgres:postgres /backups

# 🔧 **Copiar el script de entrada y asignar permisos**
COPY entrypoint_pgbackup.sh /entrypoint_pgbackup.sh
RUN chmod +x /entrypoint_pgbackup.sh

# 👤 **Cambiar al usuario 'postgres' para la ejecución**
USER postgres

# 🏁 **Definir el entrypoint**
ENTRYPOINT ["/entrypoint_pgbackup.sh"]
