# 🏗️ Usa la imagen oficial de Redis
FROM redis:latest

# 🛠️ Ejecutar como root para configurar permisos
USER root

# 📂 Crear el directorio de configuración de Redis y asignar permisos adecuados
RUN mkdir -p /etc/redis && \
    chown -R redis:redis /etc/redis

# 🔧 Copiar el entrypoint
COPY entrypoint_redis.sh /entrypoint_redis.sh
RUN chmod +x /entrypoint_redis.sh

# 👤 Cambiar al usuario 'redis' antes de ejecutar el contenedor
USER redis

# 🚀 Definir el entrypoint
ENTRYPOINT ["/entrypoint_redis.sh"]
