name: Actualizar README automáticamente

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Se ejecuta diariamente a medianoche

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Obtiene el historial completo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Ejecutar script de actualización del README
        run: |
          python update_readme.py

      - name: Configurar Git
        run: |
          git config --local user.email "jorgegr.gijon@gmail.com"
          git config --local user.name "JorgeGR"

      - name: Commit de cambios en README si hay actualizaciones
        run: |
          git add README.md
          if ! git diff --cached --quiet; then
            git commit -m "Auto-actualización del README [skip ci]"
            git push
          else
            echo "No hay cambios en el README"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.MYTOKEN }}
